### ISSUE TITLE
Not compiling with Xcode 6.3, Swift 1.2

### ISSUE THREAD

**Issue by Sajjon** [iMartinKiss/Block-KVO#28]
Hi!

Thanks for a great library! I used it heavily in an earlier project!

However, in this new project I am experiencing some difficulties due to what I believe to be Swift 1.2.

I am including Block-KVO in my podfile and importing Block-KVO into my Bridging-header file:
'#import <Block-KVO/MTKObserving.h>'

But the project won't compile due to objc_msgsend has too many arguments. This is caused by ENABLE_STRICT_OBJC_MSGSEND being set to YES by default by cocoapods. I have successfully fixed that by adding the followint post_installer script setting said flag to NO.

```ruby
post_install do |installer|
	installer.project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
		end
	end
end
```

I am getting warning 'Block-KVO/MTKObserving.h' file not found.

Just for debugging purposes I than changed that line in the Bridging-Header to use the absolut path to said file, which takes me one step further (which is strange?!?!), and yields this error in the file MTKObserving.h:
"'keypath.h' file not found"

What to do? Any idea? 

Thanks a bunch!

**Comment by iMartinKiss** [comment]
Is it related to this code in `-observeObject:property:withSelector:`?

```objc
default: {
    // +3
    // -someObject:didChangeSomethingFrom:to:
    void(*msgSend)(id, SEL, id, id, id) = (typeof(msgSend))objc_msgSend;
    msgSend(weakSelf, observationSelector, weakObject, old, new);
    break;
}
```

**Comment by Sajjon** [comment]
@iMartinKiss Exactly! As I metioned, it seams related to Cocoapods as well: https://github.com/CocoaPods/CocoaPods/issues/3060

But however, my post installer script should fix that. So it seams something else is wrong? 

Have you been able to reproduce the error? Just use XCode 6.3 Beta, Swift project with Block-KVO integrated via Cocoapods. Use Cocoapods version 0.36.0. I have iOS 8 as deployment target.

Would be amazing if this could be fixed since I really like Block-KVO :+1:  Thanks!

**Comment by iMartinKiss** [comment]
When you say _exactly_, does your code contain this line?

```objc
void(*msgSend)(id, SEL, id, id, id) = (typeof(msgSend))objc_msgSend;
```

If it doesn’t, please, pull the latest revision.

**Comment by Sajjon** [comment]
@iMartinKiss I have made an [example project](https://github.com/Sajjon/Block-KVOFails). Open it using Xcode 6.3 and use Cocoapods 0.36 or 0.36.1, fails on both.

The file (category) 'NSObject+MTKObserving.m' contains:

```objc
objc_msgSend(weakSelf, observationSelector, weakObject, old, new); // Fuck off NSInvocation!
```

**Comment by Sajjon** [comment]
@iMartinKiss As you can see in the [podfile](https://github.com/Sajjon/Block-KVOFails/blob/master/Podfile) of the [example project](https://github.com/Sajjon/Block-KVOFails) I am just using 
`
pod 'Block-KVO'
`

Which results in version 2.2.1, which results in  'NSObject+MTKObserving.m' containing:
```objc
objc_msgSend(weakSelf, observationSelector, weakObject, old, new); // Fuck off NSInvocation!
```

So how do I achieve:
```objc
void(*msgSend)(id, SEL, id, id, id) = (typeof(msgSend))objc_msgSend;
```
?

Thanks a lot! :smile:

**Comment by iMartinKiss** [comment]
Version on CocoaPods is not up to date and it will never be updated again. You should use this repositary directly, the latest commit is correct.

**Comment by Sajjon** [comment]
@iMartinKiss ah okay! Sorry I did not know that. Maybe you can add that info to the README? And also how to "use this repository directly" - can you point me the correct direction on how to do that? 

Thanks a bunch!

**Comment by mauriciomassaia** [comment]
on my Podfile i tried: 
```pod
platform :ios, '7.0'

target "GeLoBeaconOTAConfiguration" do
    # pod "Block-KVO", "~> 2.2.1"
    pod 'Block-KVO', :git => 'https://github.com/iMartinKiss/Block-KVO.git'
end

target "GeLoBeaconOTAConfigurationTests" do

end
```

but im getting the same error.

My apologies if it is wrong but im new on iOS projects. I am trying to run https://github.com/GeLoInc/GeLo-OTAC-iOS .

Cheers

**Comment by orkenstein** [comment]
@iMartinKiss, why Cocoapods version will never be updated?
