### ISSUE TITLE
Compile error when included in .mm file

### ISSUE THREAD

**Issue by praveencastelino** [iMartinKiss/Block-KVO#29]
Looks like the keyword 'new' used MTKObserver.h is causing compile time error when included in .mm file.

/MyProjectPath/Pods/Headers/Public/Block-KVO/MTKObserver.h:15:84: error: expected ')'
typedef void(^MTKBlockGeneric)      (__weak id self,                            id new);
                                                                                   ^
/MyProjectPath/Pods/Headers/Public/Block-KVO/MTKObserver.h:15:37: note: to match this '('
typedef void(^MTKBlockGeneric)      (__weak id self,                            id new);
                                    ^
/MyProjectPath/Pods/Headers/Public/Block-KVO/MTKObserver.h:16:84: error: expected ')'
typedef void(^MTKBlockChange)       (__weak id self,                    id old, id new);
                                                                                   ^
/MyProjectPath/Pods/Headers/Public/Block-KVO/MTKObserver.h:16:37: note: to match this '('
typedef void(^MTKBlockChange)       (__weak id self,                    id old, id new);
                                    ^

**Comment by iMartinKiss** [comment]
This issue has been already fixed, see here [MTKObserver.h](https://github.com/iMartinKiss/Block-KVO/blob/master/Sources/MTKObserver.h). Make sure you are using the latest version.

**Comment by praveencastelino** [comment]
Oh Ok. Looks like the 'pod 'Block-KVO'  still has the old source? Anyways...i have the fix in place now. Thanks.

**Comment by iMartinKiss** [comment]
I no longer update CocoaPods central repositary. I’m sorry when this caused some issues, but you can always link to this project directly.
