### ISSUE TITLE
Can't compile 'objc_msgSend has too many arguments'

### ISSUE THREAD

**Issue by LarrrrryT** [iMartinKiss/Block-KVO#30]
![screen shot 2015-03-23 at 3 42 14 pm](https://cloud.githubusercontent.com/assets/3093650/6792214/37f5ab2e-d173-11e4-8b53-3c33a6874549.jpeg)

**Comment by iMartinKiss** [comment]
Please, make sure you use the latest version of the project.

**Comment by Sajjon** [comment]
@LarrrrryT duplicate:
https://github.com/iMartinKiss/Block-KVO/issues/28

Did you get it to work?

@iMartinKiss Can you confirm that Block KVO works using Swift 1.2? 

Thx!

**Comment by ajfigueroa** [comment]
@LarrrrryT Any update? I ran into this issue for the first time today.

The issue occurs during pod compilation for anyone interested.

**Comment by iMartinKiss** [comment]
There must be a way to reference the latest version. I don’t use CocoaPods myself, so I can only search the web for solutions.

**Comment by ehlersd** [comment]
@iMartinKiss You just need to tag a new release (ie: 2.2.3) and update your Block-KVO.podspec file in the repo.  

That should take care of it.  

I'll fork the repo and send you a pull-request...

**Comment by iMartinKiss** [comment]
Updated README with how to reference this repo directly. Added version v2.2.3.

Don’t expect me to tag every bug-fix commit with new version just because of CocoaPods.

**Comment by y0unghe** [comment]
Did this solved or not? I am looking for a solution here. But I just can't find the solution here.

**Comment by iMartinKiss** [comment]
Please, make sure you use the latest version of the project. The issue has been fixed long time ago, [see here](https://github.com/iMartinKiss/Block-KVO/blob/master/Sources/NSObject%2BMTKObserving.m#L203).

CocoaPods central repo is no longer updated (by me), to use Block-KVO, or any other repo, reference the `master` branch in your podfile.

**Comment by y0unghe** [comment]
@iMartinKiss Thanks. It worked.
