### ISSUE TITLE
Block-KVO logic should follow the same approach as original KVO

### ISSUE THREAD

**Issue by armadilov** [iMartinKiss/Block-KVO#32]
I found this issue while I was expecting KVO to be called for property change (because of pointer value change), however it wasn't.

If I'd use normal apple's KVO I'd get notification in observeValueForKeypath, but since my objects were equal Block-KVO didn't call my blocks.

Here is the code I'm refering to in MTKObserver.m:

- (void)executeAfterSettingBlocksOld:(id)old new:(id)new {
	// Here we check for equality. Two values are equal when they have equal pointers (e.g. nils) or they respond to -isEqual: with YES.
    if (old == new || (old && [new isEqual:old])) return;
    
    for (MTKBlockChange block in self.afterSettingBlocks) {
        block(self.target, old, new);
    }
}

PS. Additionaly I think that whole old == new will always be false, since original KVO will rule out this scenario.

**Comment by iMartinKiss** [comment]
Works as expected.
