### ISSUE TITLE
Macro MTKObservePropertySelf can not use with  stringWithFormat in the block

### ISSUE THREAD

**Issue by maintiendrai** [iMartinKiss/Block-KVO#34]
MTKObservePropertySelf(property.login, NSString *, {
            [NSString stringWithFormat:@"deviceId=%@", @"aaa"];
});

**Comment by iMartinKiss** [comment]
Thanks, I just commited a fix. Close this issue, if it is ok.

**Comment by maintiendrai** [comment]
OK
